name: smartphone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'


dependencies:
  
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  get: ^4.6.5
  glassmorphism:
  flutter_boxicons:
  # td_sip_plugin: ^0.0.9
  flutter_background_service: ^2.4.6
  flutter_webrtc: 
  sip_ua: 
  logger: ^1.4.0
  web_socket_channel: ^2.4.0
  fluttertoast: ^8.2.2
  mask_text_input_formatter: ^2.4.0
  intl: ^0.18.1
  vibration: ^1.8.1
  flutter_ringtone_player: ^3.2.0
  # janus_client: ^2.2.15
  # web_socket_channel: ^2.4.0
  # flutter_webrtc: ^0.9.32
  # twilio_voice: ^0.0.9
  # td_sip_plugin: ^0.0.9
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
        - assets/images/splash2.png
        - assets/
        - assets/images/
        - assets/images/logo-antiga.png
        - assets/images/logo-luigi.png

